### ISSUE TITLE
Errors after initial installation

### ISSUE THREAD

**Issue by MultiTrickFox** [julienkay/genesis#1]
I'm using the editor 2021.3.19f1 with built-in render pipeline as well, but getting the following errors right after package import.. I cant see a Genesis tab in menu, probably because of this?

<img width="1069" alt="Screen Shot 2023-02-24 at 11 28 53 AM" src="https://user-images.githubusercontent.com/39859227/221169574-5fa58145-5328-4d5b-82c2-1bac659744ab.png">

**Comment by julienkay** [comment]
Good catch, seems like I forgot to add the "com.unity.nuget.newtonsoft-json" package as a dependency. If you add that via the Package Manager, everything should be good. I'll update the package with the missing dependency.

**Comment by MultiTrickFox** [comment]
Alright. good luck on the project :)
