### ISSUE TITLE
genesis import error in unity

### ISSUE THREAD

**Issue by KaamalVN** [julienkay/genesis#11]
Packages\com.doji.genesis\Runtime\Scripts\DepthEstimator.cs(9,23): error CS0246: The type or namespace name 'NNModel' could not be found (are you missing a using directive or an assembly reference?)

**Comment by julienkay** [comment]
It sounds like you're missing the Barracuda package.
If I install the genesis package via OpenUPM, or via the unitypackage in the [releases section](https://github.com/julienkay/genesis/releases/tag/v0.2.0) the Package Manager correctly resolves the dependencies for me.
If it doesn't for you, you may be able to add the Barracuda package manually.

**Comment by KaamalVN** [comment]
Thanks mam got it working after installing the barracuda 👍
