### ISSUE TITLE
AssetImporter null error (OSX)

### ISSUE THREAD

**Issue by MultiTrickFox** [julienkay/genesis#2]
Both AssetImporter.GetAtPath()s are returning null in the DepthSkyboxPrefabUtility.cs

The error is below; the debug.log is mine for the pngTargetPath

<img width="1065" alt="Screen Shot 2023-02-24 at 1 39 26 PM" src="https://user-images.githubusercontent.com/39859227/221193285-379953c2-9925-4f33-a2ea-29c090c2a25f.png">

I believe the target path should be inside Assets/Genesis (just a guess), instead of:

<img width="791" alt="Screen Shot 2023-02-24 at 1 43 34 PM" src="https://user-images.githubusercontent.com/39859227/221193521-00c66362-bd02-453e-9b13-4c32693a6999.png">

Then again I'm using OSX, I guess its the path difference wrt windows: / vs \

**Comment by julienkay** [comment]
Good point, yeah I didn't pay close attention to cross-platform support with all the paths. If I push a branch, could you test if it works on macOS?

**Comment by julienkay** [comment]
A small single-line change should fix it. Could you try that on your end?
bcaecd8620d87127419d984669908d8f792eafd5

**Comment by MultiTrickFox** [comment]
Yep, it's working now, I see the generation.
